// See https://aka.ms/new-console-template for more information
using AdventOfCode2025;
using System.Diagnostics;

Console.WriteLine("Hello, World!");
Stopwatch sw = Stopwatch.StartNew();
Console.WriteLine($"Day 1 Part 1: {Day1.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 1 Part 2: {Day1.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 2 Part 1: {Day2.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 2 Part 2: {Day2.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 3 Part 1: {Day3.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 3 Part 2: {Day3.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 4 Part 1: {Day4.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 4 Part 2: {Day4.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 5 Part 1: {Day5.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 5 Part 2: {Day5.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 6 Part 1: {Day6.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 6 Part 2: {Day6.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 7 Part 1: {Day7.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 7 Part 2: {Day7.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 8 Part 1: {Day8.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 8 Part 2: {Day8.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 9 Part 1: {Day9.Puzzle1()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
Console.WriteLine($"Day 9 Part 2: {Day9.Puzzle2()} \n\r Time: {sw.Elapsed.Milliseconds}");
sw.Restart();
sw.Stop();
